=== laithihanh/Java/Xml/Lap2/src/Tulam2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT houses (house*)>
<!ELEMENT house (room+)>
    <!ELEMENT room (dimenssions,windows,furniture)>    
        <!ELEMENT dimenssions (with,length)>
            <!ELEMENT length (#PCDATA)>
        <!ELEMENT windows (window*)>
            <!ELEMENT window (elevation,with,height)>
                <!ELEMENT with (#PCDATA)>
                <!ELEMENT height (#PCDATA)> 
                <!ELEMENT elevation EMPTY>
        <!ELEMENT furniture (#PCDATA)>
    <!ATTLIST room name ID #REQUIRED colour IDREF #IMPLIED >
    <!ATTLIST elevation facing (north | south | east | west) #REQUIRED>

=== laithihanh/Java/Xml/Lap2/src/Tulam2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE houses SYSTEM "Tulam2.dtd">
<houses>
    <house>
        <room name="njhj">
            <dimenssions>
                <with>110</with>
                <length>220</length>
            </dimenssions>
            <windows>
                <window>
                    <elevation facing="west"></elevation>
                    <with>110</with>
                    <height>220</height>
                </window>
            </windows>
            <furniture>avr</furniture>
        </room>
    </house>
</houses>
